import Head from 'next/head'
import { Header } from '@/components/Header'
import { Footer } from '@/components/Footer'
import style from "../styles/Home.module.css";

export default function Home() {
	return (
		<>
			<Head>
				<title>Aboutについて</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

      		<Header />

      		<main>
				<section Id={style.about}>
					<div className={style.container}>
						<h1>About Me</h1>
						<p>Welcome to my portfolio website! I am a web developer with a passion for creating beautiful and functional websites. I specialize in HTML, CSS, and JavaScript, and I am constantly learning and exploring new technologies.</p>
					</div>
				</section>
          
				<section Id={style.portfolio}>
					<div className={style.container}>
						<h1>My Portfolio</h1>
						<div className={style.portfolioItems}>
							<div className={style.item}>
								<img src="img/flower.jpg" alt="Project 1" />
								<h3>Project 1</h3>
								<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
							</div>
							<div className={style.item}>
								<img src="img/flower.jpg" alt="Project 2" />
								<h3>Project 2</h3>
								<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
							</div>
							<div className={style.item}>
								<img src="img/flower.jpg" alt="Project 3" />
								<h3>Project 3</h3>
								<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
							</div>
						</div>
					</div>
				</section>
      		</main>

      		<Footer />
		</>
	)
}
